/*
 * This source file was generated by the Gradle 'init' task
 */
package com.irb.migration;

import com.google.inject.Guice;
import com.irb.migration.service.ETL;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.setProperty("eclipselink.ddl-generation", "update");
        ETL etl = Guice.createInjector().getInstance(ETL.class);
        etl.StartETL();
        System.out.println(new App().getGreeting());
    }
}
